# -*- coding: UTF-8 -*-


from .project import *


ENV_PREFIX          = f"{SYM_TSHRAG.upper()}_"

ENV_HOST            = f"{ENV_PREFIX}HOST"

ENV_TEST_ID         = f"{ENV_PREFIX}TEST_ID"
ENV_TEST_MACHINE    = f"{ENV_PREFIX}TEST_MACHINE"
ENV_TEST_DEVICE     = f"{ENV_PREFIX}TEST_DEVICE"
ENV_TEST_DIR        = f"{ENV_PREFIX}TEST_DIR"

ENV_JOB_ID          = f"{ENV_PREFIX}JOB_ID"
ENV_JOB_MACHINE     = f"{ENV_PREFIX}JOB_MACHINE"
ENV_JOB_DEVICE      = f"{ENV_PREFIX}JOB_DEVICE"
ENV_JOB_DIR         = f"{ENV_PREFIX}JOB_DIR"

