# -*- coding: UTF-8 -*-


SYM_TSHRAG          = "tshrag"

PROJECT_NAME        = SYM_TSHRAG.capitalize()
PROJECT_DESCRIPTION = ""
PROJECT_VERSION_MAJOR = 0
PROJECT_VERSION_MINOR = 0
PROJECT_VERSION_REV = 0
PROJECT_VERSION     = f"v{PROJECT_VERSION_MAJOR}.{PROJECT_VERSION_MINOR}.{PROJECT_VERSION_REV}"
